### ISSUE TITLE
Stylesheet not working after converting the mdx file to wikit file.

### ISSUE THREAD

**Issue by Eason-YC-Huang** [ikey4u/wikit#14] opened 2023-03-07 12:15 UTC
It seems like wikit only recognize the wikit format dictionary.
So I had to convert my mdx file to wikit file using this command `./wikit dict --create -o ./LDOCE5.wikit LDOCE5.mdx`  and loaded it into wikit desktop. 
But in the end, I found that the style is quite different between the Eudict and the Wikit Desktop.
Did i do something wrong ?

![image](https://user-images.githubusercontent.com/40693388/223417011-a11c2ce4-6541-4d20-a3ed-8aec07ee4483.png)

**Comment by ikey4u** [comment] 2023-03-07 13:23
@Eason-YC-Huang  

1. Open wikit configuration directory, remove the `static/` cache directory and restart wikit to see if the problem disappeared.

2. If the method above does not work, one possible reason is that your mdx file does not contain any css file and the css file is provided in another file such as `LDOCE5.css`. If you are in this case, you can first convert mdx into text (`./wikit dict -c -o LDOCE5.txt LDOCE5.mdx `) and create wikit dictionary from this text and its css file. See [here](https://github.com/ikey4u/wikit/wiki) for detail instructions.

3. If you are sure that your mdx contains css style, you can join QQ group 546132895 or email with me your mdx file, and then I will try to figure out what happens.

**Comment by ikey4u** [comment] 2023-04-01 05:42
Since there is not active on this thread, I'll close this issue if someday you can provide me more information to reproduce the issue, you can reopen again.

**Closed as completed by ikey4u** 2023-04-01 05:42 UTC

**Comment by Congee** [comment] 2023-07-16 03:14
It didn't work for me either. Somehow wikit did not respect [css] and [js] fields in the .toml config alongside a .wikit file. After I manually copy the contents .css and .js files into those counterpart .js & .css files in the static/ cache directory, the css and js files started to work.

Not sure this is the same case as yours, but hope it helps.

The css & js files in static/ shall not be empty.
<img width="450" alt="image" src="https://github.com/ikey4u/wikit/assets/2083950/329bd8b0-72b6-4132-986a-cd0aeb9fc6f7">

**Comment by ikey4u** [comment] 2023-07-16 12:12
@Congee Hi, can you give me a minimal example to reproduce the problem?
